import re
from typing import List, Dict
from .spec import ExpectedColumnItem, BaseSpec, Type


class MetabolomicsSpec(BaseSpec):
    @property
    def version(self) -> str:
        return "2022070101"

    @property
    def description(self) -> str:
        return """For each uploaded file, please fulfill the related information of them on the file named as "metadata.xlsx". This file offers the information of each column included in the "metadata.xlsx".\nIf you have any questions, please feel free to contact us at quartet@fudan.edu.cn. NOTE: This template table may change in the future as the specification is upgraded.
        """

    @property
    def specs(self) -> Dict[str, List[ExpectedColumnItem]]:
        return {
            "metadata": [
                ExpectedColumnItem(
                    name="file_name",
                    required=True,
                    type=Type.TEXT,
                    description="File Name",
                    procedure="Basic Info",
                    example="LabXXX_XXX_D5_1.csv",
                ),
                ExpectedColumnItem(
                    name="data_format",
                    required=True,
                    type=Type.CATEGORY,
                    description="Data Format",
                    procedure="Basic Info",
                    example="CSV",
                    options=["mzXML", "mzML", "CSV"],
                ),
                ExpectedColumnItem(
                    name="file_size",
                    required=True,
                    type=Type.NUMBER,
                    procedure="Basic Info",
                    min=0,
                    max=100000000000,
                    description="File Size (Bytes)",
                    example=10000,
                ),
                ExpectedColumnItem(
                    name="md5sum",
                    required=True,
                    type=Type.TEXT,
                    procedure="Basic Info",
                    regex=re.compile(r"^[a-f0-9]{32}$"),
                    description="MD5 Checksum",
                    example="de24a560a1178a5e59085b5b70ef2e35",
                ),
                ExpectedColumnItem(
                    name="sample_id",
                    required=True,
                    type=Type.CATEGORY,
                    options=[
                        "D5",
                        "D6",
                        "D7",
                        "D8",
                    ],
                    procedure="Basic Info",
                    description="Sample ID",
                    example="D5",
                ),
                ExpectedColumnItem(
                    name="study_id",
                    required=True,
                    type=Type.TEXT,
                    procedure="Basic Info",
                    description="Study ID",
                    example="LabXXX_XXX",
                ),
                ExpectedColumnItem(
                    name="strategy",
                    required=True,
                    type=Type.CATEGORY,
                    options=["Targeted", "MRM_based_targeted", "Untargeted"],
                    procedure="Basic Info",
                    description="Strategy",
                    example="Targeted",
                ),
                ExpectedColumnItem(
                    name="analysis_time",
                    required=True,
                    type=Type.NUMBER,
                    min=0,
                    max=1000,
                    procedure="Basic Info",
                    description="Time for each analysis (minutes)",
                    example=30,
                ),
                ExpectedColumnItem(
                    name="total_analysis",
                    required=True,
                    type=Type.NUMBER,
                    min=0,
                    max=1000,
                    procedure="Basic Info",
                    description="Total Analysis for Each Sample",
                    example=2,
                ),
                ExpectedColumnItem(
                    name="prepare_date",
                    required=True,
                    type=Type.NUMBER,
                    min=20150101,
                    max=20361231,
                    procedure="Sample Preparation",
                    description="Date for Sample Preparation",
                    example=20210808,
                ),
                ExpectedColumnItem(
                    name="qc_samples",
                    required=True,
                    type=Type.TEXT,
                    procedure="Sample Preparation",
                    description="QC Samples",
                    example="Pool created by taking a small aliquot from every test sample, aliquot of ultra-pure water and aliquot of solvents used in extraction.",
                ),
                ExpectedColumnItem(
                    name="solvent",
                    required=True,
                    type=Type.TEXT,
                    procedure="Sample Preparation",
                    description="Solvent to Reconstitute Extracts",
                    example="methanol:water (6:1) solution",
                ),
                ExpectedColumnItem(
                    name="solvent_vol",
                    required=True,
                    type=Type.NUMBER,
                    min=0,
                    max=1000,
                    procedure="Sample Preparation",
                    description="Volume of Solvent (uL)",
                    example=50,
                ),
                ExpectedColumnItem(
                    name="prepare_detail",
                    required=True,
                    type=Type.TEXT,
                    description="Details for Sample Preparation",
                    procedure="Sample Preparation",
                    example="The plate was stored at -20°Cfor 20 minutes and followed by 4000g centrifugation at 4 °C for 30 minutes. 135μL of supernatant was transferred to a new 96-well plate with 15μL internal standards in each well. Serial dilutions of derivatized stock standards were added to the left wells. Finally the plate was sealed for LC-MS analysis.",
                ),
                ExpectedColumnItem(
                    name="injection_vol",
                    required=True,
                    type=Type.NUMBER,
                    min=0,
                    max=1000,
                    description="Injection Volume (uL)",
                    procedure="Sample Preparation",
                    example=4,
                ),
                ExpectedColumnItem(
                    name="injection_order",
                    required=True,
                    type=Type.NUMBER,
                    min=0,
                    max=100,
                    description="Injection Order",
                    procedure="Sample Preparation",
                    example=1,
                ),
                ExpectedColumnItem(
                    name="chromatography_type",
                    required=True,
                    type=Type.TEXT,
                    description="Chromatography Type",
                    procedure="Chromatography",
                    example="UPLC",
                ),
                ExpectedColumnItem(
                    name="chromatography_instrument",
                    required=True,
                    type=Type.TEXT,
                    description="Instrument Name",
                    procedure="Chromatography",
                    example="Waters ACQUITY UPLC",
                ),
                ExpectedColumnItem(
                    name="chromatography_column",
                    required=True,
                    type=Type.TEXT,
                    description="Column Name",
                    procedure="Chromatography",
                    example="ACQUITY UPLC BEH C18 1.7 μM VanGuard pre-column (2.1×5 mm) and ACQUITY UPLC BEH C18 1.7 μM analytical column (2.1 ×100 mm)",
                ),
                ExpectedColumnItem(
                    name="column_temp",
                    required=True,
                    type=Type.NUMBER,
                    min=0,
                    max=100,
                    description="Column Temperature (°C)",
                    procedure="Chromatography",
                    example=40,
                ),
                ExpectedColumnItem(
                    name="sample_manager_temp",
                    required=True,
                    type=Type.NUMBER,
                    min=0,
                    max=100,
                    description="Sample Manager Temperature (°C)",
                    procedure="Chromatography",
                    example=10,
                ),
                ExpectedColumnItem(
                    name="mobile_phases",
                    required=True,
                    type=Type.TEXT,
                    description="Mobile Phases",
                    procedure="Chromatography",
                    example="A=water with 0.1% formic acid; and B=acetonitrile / IPA (90:10)",
                ),
                ExpectedColumnItem(
                    name="flow_rate",
                    required=True,
                    type=Type.FLOAT,
                    min=0.1,
                    max=10.0,
                    description="Flow Rate (mL/min)",
                    procedure="Chromatography",
                    example=0.4,
                ),
                ExpectedColumnItem(
                    name="gradient_conditions",
                    required=True,
                    type=Type.TEXT,
                    description="Gradient Conditions",
                    procedure="Chromatography",
                    example="0-1 min (5% B), 1-12 min (5-80% B), 12-15 min (80-95% B), 15-16 min (95-100%B), 16-18 min (100%B), 18-18.1 min (100-5% B), 18.1-20 min (5% B).",
                ),
                ExpectedColumnItem(
                    name="capillary",
                    required=True,
                    type=Type.TEXT,
                    description="Capillary(Kv)",
                    procedure="MS",
                    example="1.5 (ESI+), 2.0 (ESI-)",
                ),
                ExpectedColumnItem(
                    name="ms_instrument_type",
                    required=True,
                    type=Type.TEXT,
                    description="Instrument Type",
                    procedure="MS",
                    example="Triple quadrupole",
                ),
                ExpectedColumnItem(
                    name="ms_instrument_name",
                    required=True,
                    type=Type.TEXT,
                    description="Instrument Name",
                    procedure="MS",
                    example="Xevo TQ-S",
                ),
                ExpectedColumnItem(
                    name="ion_mode",
                    required=True,
                    type=Type.CATEGORY,
                    options=["POSITIVE", "NEGATIVE", "UNSPECIFIED"],
                    description="Ion Mode",
                    procedure="MS",
                    example="POSITIVE",
                ),
                ExpectedColumnItem(
                    name="ms_detail",
                    required=True,
                    type=Type.TEXT,
                    description="Details for MS",
                    procedure="MS",
                    example="The MS analysis alternated between MS and data-dependent MSn scans using dynamic exclusion.  The scan range varied slighted between methods but covered 70-1000 m/z.",
                ),
                ExpectedColumnItem(
                    name="mi_database",
                    required=True,
                    type=Type.CATEGORY,
                    options=["HMDB", "InHouse"],
                    description="Database for Metabolite Identification",
                    procedure="Data Analysis",
                    example="HMDB",
                ),
                ExpectedColumnItem(
                    name="mi_criteria",
                    required=True,
                    type=Type.TEXT,
                    description="Criteria for Metabolite Identification",
                    procedure="Data Analysis",
                    example="Retention index within a narrow RI window of the proposed identification, accurate mass match to the library +/- 10 ppm, and the MS/MS forward and reverse scores between the experimental data and authentic standards",
                ),
                ExpectedColumnItem(
                    name="mq_units",
                    required=True,
                    type=Type.TEXT,
                    description="Metabolite Quantification Units",
                    procedure="Data Analysis",
                    example="Intensity",
                ),
                ExpectedColumnItem(
                    name="mq_normalization",
                    required=True,
                    type=Type.TEXT,
                    description="Metabolite Quantification Normalization",
                    procedure="Data Analysis",
                    example="Each compound was corrected in run-day blocks by registering the medians to equal one (1.00) and normalizing each data point proportionately",
                ),
            ]
        }
